# Site settings
title: Software and Programming Language Theory
email: maxim.krivchikov@gmail.com
description: "

"
baseurl: "/programming-languages/" # the subpath of your site, e.g. /blog/
url: "https://maxxk.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  maxxk

# Build settings
markdown: kramdown
exclude: [ "presentations/*.md" ]
keep_files: [ "presentations/*.html" ]
